module.exports = {
  PARAM_2_DRAW: "PARAM_2_DRAW",
  PATH_CHANGE: "PATH_CHANGE",
  DRAW_CHANGE: "DRAW_CHANGE",
  DRAW_SELECTION_CHANGE: "DRAW_SELECTION_CHANGE",
  PATH_SELECTION_CHANGE: "PATH_SELECTION_CHANGE"

};

